//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WcfUnit.VSIntegration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WcfUnit.VSIntegration.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action executed is inconsistent with the state of the corresponding button.
        /// </summary>
        internal static string ButtonStateInconsistency {
            get {
                return ResourceManager.GetString("ButtonStateInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test generation error.
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating the unit test code.
        /// </summary>
        internal static string GenerationError {
            get {
                return ResourceManager.GetString("GenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message log did not contain any calls to WCF services.
        /// </summary>
        internal static string NoSoapActions {
            get {
                return ResourceManager.GetString("NoSoapActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Log File Problem.
        /// </summary>
        internal static string NoSoapActionsMessageBoxTitle {
            get {
                return ResourceManager.GetString("NoSoapActionsMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move to this page as it is not enabled..
        /// </summary>
        internal static string PageStateInconsistency {
            get {
                return ResourceManager.GetString("PageStateInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while setting up or running the program under test.
        /// </summary>
        internal static string ProgramSetupAndExecutionErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ProgramSetupAndExecutionErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing message log file.
        /// </summary>
        internal static string TraceFileParseErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("TraceFileParseErrorMessageBoxTitle", resourceCulture);
            }
        }
    }
}
