//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddRequest", Namespace="http://contoso.com/data/test")]
    public partial class AddRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AField;
        
        private int BField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A
        {
            get
            {
                return this.AField;
            }
            set
            {
                this.AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int B
        {
            get
            {
                return this.BField;
            }
            set
            {
                this.BField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://contoso.com/data/test")]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AnswerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestHeader", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public partial class TestHeader : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HeaderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseServiceKnownType", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.DerivedServiceKnownType))]
    public partial class BaseServiceKnownType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BasePropertyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseProperty
        {
            get
            {
                return this.BasePropertyField;
            }
            set
            {
                this.BasePropertyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DerivedServiceKnownType", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public partial class DerivedServiceKnownType : GeneratedContracts.BaseServiceKnownType
    {
        
        private string DerivedPropertyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DerivedProperty
        {
            get
            {
                return this.DerivedPropertyField;
            }
            set
            {
                this.DerivedPropertyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionsData", Namespace="http://contoso.com/data/test")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.MarshalByRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.TestHeader))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.DerivedServiceKnownType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.BaseServiceKnownType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.AddRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.AddRequest[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Shape))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Circle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Rectangle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.MemoryStream))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.Stream))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest>))]
    public partial class CollectionsData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object[] ArrayListField;
        
        private System.Xml.XmlElement ElementField;
        
        private System.Collections.Generic.Dictionary<object, object> HashtableField;
        
        private int[] IntIListField;
        
        private int[] IntListField;
        
        private System.Xml.XmlNode[] NodesField;
        
        private object[] NonGenericEnumerableOnlyCollectionField;
        
        private GeneratedContracts.AddRequest[] RequestCollectionField;
        
        private System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest> RequestDictionaryField;
        
        private GeneratedContracts.AddRequest[] RequestICollectionField;
        
        private System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest> RequestIDictionaryField;
        
        private GeneratedContracts.AddRequest[] RequestIListField;
        
        private GeneratedContracts.AddRequest[] RequestListField;
        
        private object SqlDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] ArrayList
        {
            get
            {
                return this.ArrayListField;
            }
            set
            {
                this.ArrayListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement Element
        {
            get
            {
                return this.ElementField;
            }
            set
            {
                this.ElementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, object> Hashtable
        {
            get
            {
                return this.HashtableField;
            }
            set
            {
                this.HashtableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] IntIList
        {
            get
            {
                return this.IntIListField;
            }
            set
            {
                this.IntIListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] IntList
        {
            get
            {
                return this.IntListField;
            }
            set
            {
                this.IntListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.NodesField;
            }
            set
            {
                this.NodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] NonGenericEnumerableOnlyCollection
        {
            get
            {
                return this.NonGenericEnumerableOnlyCollectionField;
            }
            set
            {
                this.NonGenericEnumerableOnlyCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeneratedContracts.AddRequest[] RequestCollection
        {
            get
            {
                return this.RequestCollectionField;
            }
            set
            {
                this.RequestCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest> RequestDictionary
        {
            get
            {
                return this.RequestDictionaryField;
            }
            set
            {
                this.RequestDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeneratedContracts.AddRequest[] RequestICollection
        {
            get
            {
                return this.RequestICollectionField;
            }
            set
            {
                this.RequestICollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest> RequestIDictionary
        {
            get
            {
                return this.RequestIDictionaryField;
            }
            set
            {
                this.RequestIDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeneratedContracts.AddRequest[] RequestIList
        {
            get
            {
                return this.RequestIListField;
            }
            set
            {
                this.RequestIListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeneratedContracts.AddRequest[] RequestList
        {
            get
            {
                return this.RequestListField;
            }
            set
            {
                this.RequestListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SqlData
        {
            get
            {
                return this.SqlDataField;
            }
            set
            {
                this.SqlDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shape", Namespace="http://contoso.com/data/test")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Circle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GeneratedContracts.Rectangle))]
    public partial class Shape : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ColourField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Colour
        {
            get
            {
                return this.ColourField;
            }
            set
            {
                this.ColourField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Circle", Namespace="http://contoso.com/data/test")]
    public partial class Circle : GeneratedContracts.Shape
    {
        
        private int RadiusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Radius
        {
            get
            {
                return this.RadiusField;
            }
            set
            {
                this.RadiusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rectangle", Namespace="http://contoso.com/data/test")]
    public partial class Rectangle : GeneratedContracts.Shape
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.IArithmetic")]
    public interface IArithmetic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/Add", ReplyAction="http://contoso.com/service/test/IArithmetic/AddResponse")]
        GeneratedContracts.Response Add(GeneratedContracts.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/Add2", ReplyAction="http://contoso.com/service/test/IArithmetic/Add2Response")]
        int Add2(GeneratedContracts.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/Add3", ReplyAction="http://contoso.com/service/test/IArithmetic/Add3Response")]
        int Add3(int a, int b);
        
        // CODEGEN: Generating message contract since the operation WrappedAdd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/WrappedAdd", ReplyAction="http://contoso.com/service/test/IArithmetic/WrappedAddResponse")]
        GeneratedContracts.WrappedAddResponse WrappedAdd(GeneratedContracts.AddRequestWrappedMessage request);
        
        // CODEGEN: Generating message contract since the operation WrappednoCustomNamesAdd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/WrappednoCustomNamesAdd", ReplyAction="http://contoso.com/service/test/IArithmetic/WrappednoCustomNamesAddResponse")]
        GeneratedContracts.WrappednoCustomNamesAddResponse WrappednoCustomNamesAdd(GeneratedContracts.AddRequestWrappedMessageNoCustomNames request);
        
        // CODEGEN: Generating message contract since the operation WrappedMessageWithHeaderAndBodyNamespaceOverrides is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/WrappedMessageWithHeaderAndBodyNamesp" +
            "aceOverrides", ReplyAction="http://contoso.com/service/test/IArithmetic/WrappedMessageWithHeaderAndBodyNamesp" +
            "aceOverridesResponse")]
        GeneratedContracts.WrappedMessageWithHeaderAndBodyNamespaceOverridesResponse WrappedMessageWithHeaderAndBodyNamespaceOverrides(GeneratedContracts.AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides request);
        
        // CODEGEN: Generating message contract since the operation UnwrappedAdd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/UnwrappedAdd", ReplyAction="http://contoso.com/service/test/IArithmetic/UnwrappedAddResponse")]
        GeneratedContracts.UnwrappedAddResponse UnwrappedAdd(GeneratedContracts.AddRequestUnwrappedMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/NoParameters", ReplyAction="http://contoso.com/service/test/IArithmetic/NoParametersResponse")]
        void NoParameters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/RefParameter", ReplyAction="http://contoso.com/service/test/IArithmetic/RefParameterResponse")]
        void RefParameter(ref int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/RefObjectParameter", ReplyAction="http://contoso.com/service/test/IArithmetic/RefObjectParameterResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.TestHeader))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.DerivedServiceKnownType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.BaseServiceKnownType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.AddRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.CollectionsData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.AddRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.Shape))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.Circle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneratedContracts.Rectangle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IO.MemoryStream))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IO.Stream))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, GeneratedContracts.AddRequest>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        void RefObjectParameter(object a, ref object b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/OutParameter", ReplyAction="http://contoso.com/service/test/IArithmetic/OutParameterResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="a")]
        int OutParameter(out int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IArithmetic/MixedDirectionParameters", ReplyAction="http://contoso.com/service/test/IArithmetic/MixedDirectionParametersResponse")]
        void MixedDirectionParameters(int a, ref int b, out int c);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://contoso.com/service/test/IArithmetic/OneWayOperation")]
        void OneWayOperation(int a);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://wrapper/", IsWrapped=true)]
    public partial class AddRequestWrappedMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public GeneratedContracts.TestHeader header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public int A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=1)]
        public int B;
        
        public AddRequestWrappedMessage()
        {
        }
        
        public AddRequestWrappedMessage(GeneratedContracts.TestHeader header, int A, int B)
        {
            this.header = header;
            this.A = A;
            this.B = B;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WrappedAddResponse
    {
        
        public WrappedAddResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddRequestWrappedMessageNoCustomNames", WrapperNamespace="http://contoso.com/service/test", IsWrapped=true)]
    public partial class AddRequestWrappedMessageNoCustomNames
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public GeneratedContracts.TestHeader header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public int A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=1)]
        public int B;
        
        public AddRequestWrappedMessageNoCustomNames()
        {
        }
        
        public AddRequestWrappedMessageNoCustomNames(GeneratedContracts.TestHeader header, int A, int B)
        {
            this.header = header;
            this.A = A;
            this.B = B;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WrappednoCustomNamesAddResponse
    {
        
        public WrappednoCustomNamesAddResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://overrideswrapper/", IsWrapped=true)]
    public partial class AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://override1")]
        public GeneratedContracts.TestHeader header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://override2", Order=0)]
        public int A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://override3", Order=1)]
        public int B;
        
        public AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides()
        {
        }
        
        public AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides(GeneratedContracts.TestHeader header, int A, int B)
        {
            this.header = header;
            this.A = A;
            this.B = B;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WrappedMessageWithHeaderAndBodyNamespaceOverridesResponse
    {
        
        public WrappedMessageWithHeaderAndBodyNamespaceOverridesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequestUnwrappedMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public GeneratedContracts.TestHeader header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public int A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=1)]
        public int B;
        
        public AddRequestUnwrappedMessage()
        {
        }
        
        public AddRequestUnwrappedMessage(GeneratedContracts.TestHeader header, int A, int B)
        {
            this.header = header;
            this.A = A;
            this.B = B;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnwrappedAddResponse
    {
        
        public UnwrappedAddResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IArithmeticChannel : GeneratedContracts.IArithmetic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ArithmeticClient : System.ServiceModel.ClientBase<GeneratedContracts.IArithmetic>, GeneratedContracts.IArithmetic
    {
        
        public ArithmeticClient()
        {
        }
        
        public ArithmeticClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ArithmeticClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ArithmeticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ArithmeticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public GeneratedContracts.Response Add(GeneratedContracts.AddRequest request)
        {
            return base.Channel.Add(request);
        }
        
        public int Add2(GeneratedContracts.AddRequest request)
        {
            return base.Channel.Add2(request);
        }
        
        public int Add3(int a, int b)
        {
            return base.Channel.Add3(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.WrappedAddResponse GeneratedContracts.IArithmetic.WrappedAdd(GeneratedContracts.AddRequestWrappedMessage request)
        {
            return base.Channel.WrappedAdd(request);
        }
        
        public void WrappedAdd(GeneratedContracts.TestHeader header, int A, int B)
        {
            GeneratedContracts.AddRequestWrappedMessage inValue = new GeneratedContracts.AddRequestWrappedMessage();
            inValue.header = header;
            inValue.A = A;
            inValue.B = B;
            GeneratedContracts.WrappedAddResponse retVal = ((GeneratedContracts.IArithmetic)(this)).WrappedAdd(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.WrappednoCustomNamesAddResponse GeneratedContracts.IArithmetic.WrappednoCustomNamesAdd(GeneratedContracts.AddRequestWrappedMessageNoCustomNames request)
        {
            return base.Channel.WrappednoCustomNamesAdd(request);
        }
        
        public void WrappednoCustomNamesAdd(GeneratedContracts.TestHeader header, int A, int B)
        {
            GeneratedContracts.AddRequestWrappedMessageNoCustomNames inValue = new GeneratedContracts.AddRequestWrappedMessageNoCustomNames();
            inValue.header = header;
            inValue.A = A;
            inValue.B = B;
            GeneratedContracts.WrappednoCustomNamesAddResponse retVal = ((GeneratedContracts.IArithmetic)(this)).WrappednoCustomNamesAdd(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.WrappedMessageWithHeaderAndBodyNamespaceOverridesResponse GeneratedContracts.IArithmetic.WrappedMessageWithHeaderAndBodyNamespaceOverrides(GeneratedContracts.AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides request)
        {
            return base.Channel.WrappedMessageWithHeaderAndBodyNamespaceOverrides(request);
        }
        
        public void WrappedMessageWithHeaderAndBodyNamespaceOverrides(GeneratedContracts.TestHeader header, int A, int B)
        {
            GeneratedContracts.AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides inValue = new GeneratedContracts.AddRequestWrappedMessageWithHeaderAndBodyNamespaceOverrides();
            inValue.header = header;
            inValue.A = A;
            inValue.B = B;
            GeneratedContracts.WrappedMessageWithHeaderAndBodyNamespaceOverridesResponse retVal = ((GeneratedContracts.IArithmetic)(this)).WrappedMessageWithHeaderAndBodyNamespaceOverrides(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.UnwrappedAddResponse GeneratedContracts.IArithmetic.UnwrappedAdd(GeneratedContracts.AddRequestUnwrappedMessage request)
        {
            return base.Channel.UnwrappedAdd(request);
        }
        
        public void UnwrappedAdd(GeneratedContracts.TestHeader header, int A, int B)
        {
            GeneratedContracts.AddRequestUnwrappedMessage inValue = new GeneratedContracts.AddRequestUnwrappedMessage();
            inValue.header = header;
            inValue.A = A;
            inValue.B = B;
            GeneratedContracts.UnwrappedAddResponse retVal = ((GeneratedContracts.IArithmetic)(this)).UnwrappedAdd(inValue);
        }
        
        public void NoParameters()
        {
            base.Channel.NoParameters();
        }
        
        public void RefParameter(ref int a)
        {
            base.Channel.RefParameter(ref a);
        }
        
        public void RefObjectParameter(object a, ref object b)
        {
            base.Channel.RefObjectParameter(a, ref b);
        }
        
        public int OutParameter(out int b)
        {
            return base.Channel.OutParameter(out b);
        }
        
        public void MixedDirectionParameters(int a, ref int b, out int c)
        {
            base.Channel.MixedDirectionParameters(a, ref b, out c);
        }
        
        public void OneWayOperation(int a)
        {
            base.Channel.OneWayOperation(a);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.ICollections")]
    public interface ICollections
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/ICollections/ProcessCollection", ReplyAction="http://contoso.com/service/test/ICollections/ProcessCollectionResponse")]
        GeneratedContracts.CollectionsData ProcessCollection(GeneratedContracts.CollectionsData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICollectionsChannel : GeneratedContracts.ICollections, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CollectionsClient : System.ServiceModel.ClientBase<GeneratedContracts.ICollections>, GeneratedContracts.ICollections
    {
        
        public CollectionsClient()
        {
        }
        
        public CollectionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CollectionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CollectionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CollectionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public GeneratedContracts.CollectionsData ProcessCollection(GeneratedContracts.CollectionsData data)
        {
            return base.Channel.ProcessCollection(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.IBufferedStreamService")]
    public interface IBufferedStreamService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedStreamOperation", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedStreamOperationRes" +
            "ponse")]
        System.IO.Stream BufferedStreamOperation(System.IO.Stream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedMemoryStreamOperat" +
            "ion", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedMemoryStreamOperat" +
            "ionResponse")]
        System.IO.MemoryStream BufferedMemoryStreamOperation(System.IO.MemoryStream input);
        
        // CODEGEN: Generating message contract since the operation BufferedUnwrappedMessageWithStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedUnwrappedMessageWi" +
            "thStream", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedUnwrappedMessageWi" +
            "thStreamResponse")]
        GeneratedContracts.BufferedUnwrappedMessageWithStreamResponse BufferedUnwrappedMessageWithStream(GeneratedContracts.BufferedUnwrappedMessageWithStream request);
        
        // CODEGEN: Generating message contract since the operation BufferedUnwrappedMessageWithMemoryStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedUnwrappedMessageWi" +
            "thMemoryStream", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedUnwrappedMessageWi" +
            "thMemoryStreamResponse")]
        GeneratedContracts.BufferedUnwrappedMessageWithMemoryStreamResponse BufferedUnwrappedMessageWithMemoryStream(GeneratedContracts.BufferedUnwrappedMessageWithMemoryStream request);
        
        // CODEGEN: Generating message contract since the operation BufferedWrappedMessageWithStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedWrappedMessageWith" +
            "Stream", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedWrappedMessageWith" +
            "StreamResponse")]
        GeneratedContracts.BufferedWrappedMessageWithStreamResponse BufferedWrappedMessageWithStream(GeneratedContracts.BufferedWrappedMessageWithStream request);
        
        // CODEGEN: Generating message contract since the operation BufferedWrappedMessageWithMemoryStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IBufferedStreamService/BufferedWrappedMessageWith" +
            "MemoryStream", ReplyAction="http://contoso.com/service/test/IBufferedStreamService/BufferedWrappedMessageWith" +
            "MemoryStreamResponse")]
        GeneratedContracts.BufferedWrappedMessageWithMemoryStreamResponse BufferedWrappedMessageWithMemoryStream(GeneratedContracts.BufferedWrappedMessageWithMemoryStream request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedUnwrappedMessageWithStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.Stream Body1;
        
        public BufferedUnwrappedMessageWithStream()
        {
        }
        
        public BufferedUnwrappedMessageWithStream(int Header, System.IO.Stream Body1)
        {
            this.Header = Header;
            this.Body1 = Body1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedUnwrappedMessageWithStreamResponse
    {
        
        public BufferedUnwrappedMessageWithStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedUnwrappedMessageWithMemoryStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.MemoryStream Body2;
        
        public BufferedUnwrappedMessageWithMemoryStream()
        {
        }
        
        public BufferedUnwrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body2)
        {
            this.Header = Header;
            this.Body2 = Body2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedUnwrappedMessageWithMemoryStreamResponse
    {
        
        public BufferedUnwrappedMessageWithMemoryStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://wrapper/BufferedWrappedMessageWithStream", IsWrapped=true)]
    public partial class BufferedWrappedMessageWithStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public byte[] Body3;
        
        public BufferedWrappedMessageWithStream()
        {
        }
        
        public BufferedWrappedMessageWithStream(int Header, byte[] Body3)
        {
            this.Header = Header;
            this.Body3 = Body3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedWrappedMessageWithStreamResponse
    {
        
        public BufferedWrappedMessageWithStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://wrapper/BufferedWrappedMessageWithMemoryStream", IsWrapped=true)]
    public partial class BufferedWrappedMessageWithMemoryStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.MemoryStream Body4;
        
        public BufferedWrappedMessageWithMemoryStream()
        {
        }
        
        public BufferedWrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body4)
        {
            this.Header = Header;
            this.Body4 = Body4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BufferedWrappedMessageWithMemoryStreamResponse
    {
        
        public BufferedWrappedMessageWithMemoryStreamResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IBufferedStreamServiceChannel : GeneratedContracts.IBufferedStreamService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BufferedStreamServiceClient : System.ServiceModel.ClientBase<GeneratedContracts.IBufferedStreamService>, GeneratedContracts.IBufferedStreamService
    {
        
        public BufferedStreamServiceClient()
        {
        }
        
        public BufferedStreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BufferedStreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BufferedStreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BufferedStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.IO.Stream BufferedStreamOperation(System.IO.Stream input)
        {
            return base.Channel.BufferedStreamOperation(input);
        }
        
        public System.IO.MemoryStream BufferedMemoryStreamOperation(System.IO.MemoryStream input)
        {
            return base.Channel.BufferedMemoryStreamOperation(input);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.BufferedUnwrappedMessageWithStreamResponse GeneratedContracts.IBufferedStreamService.BufferedUnwrappedMessageWithStream(GeneratedContracts.BufferedUnwrappedMessageWithStream request)
        {
            return base.Channel.BufferedUnwrappedMessageWithStream(request);
        }
        
        public void BufferedUnwrappedMessageWithStream(int Header, System.IO.Stream Body1)
        {
            GeneratedContracts.BufferedUnwrappedMessageWithStream inValue = new GeneratedContracts.BufferedUnwrappedMessageWithStream();
            inValue.Header = Header;
            inValue.Body1 = Body1;
            GeneratedContracts.BufferedUnwrappedMessageWithStreamResponse retVal = ((GeneratedContracts.IBufferedStreamService)(this)).BufferedUnwrappedMessageWithStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.BufferedUnwrappedMessageWithMemoryStreamResponse GeneratedContracts.IBufferedStreamService.BufferedUnwrappedMessageWithMemoryStream(GeneratedContracts.BufferedUnwrappedMessageWithMemoryStream request)
        {
            return base.Channel.BufferedUnwrappedMessageWithMemoryStream(request);
        }
        
        public void BufferedUnwrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body2)
        {
            GeneratedContracts.BufferedUnwrappedMessageWithMemoryStream inValue = new GeneratedContracts.BufferedUnwrappedMessageWithMemoryStream();
            inValue.Header = Header;
            inValue.Body2 = Body2;
            GeneratedContracts.BufferedUnwrappedMessageWithMemoryStreamResponse retVal = ((GeneratedContracts.IBufferedStreamService)(this)).BufferedUnwrappedMessageWithMemoryStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.BufferedWrappedMessageWithStreamResponse GeneratedContracts.IBufferedStreamService.BufferedWrappedMessageWithStream(GeneratedContracts.BufferedWrappedMessageWithStream request)
        {
            return base.Channel.BufferedWrappedMessageWithStream(request);
        }
        
        public void BufferedWrappedMessageWithStream(int Header, byte[] Body3)
        {
            GeneratedContracts.BufferedWrappedMessageWithStream inValue = new GeneratedContracts.BufferedWrappedMessageWithStream();
            inValue.Header = Header;
            inValue.Body3 = Body3;
            GeneratedContracts.BufferedWrappedMessageWithStreamResponse retVal = ((GeneratedContracts.IBufferedStreamService)(this)).BufferedWrappedMessageWithStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.BufferedWrappedMessageWithMemoryStreamResponse GeneratedContracts.IBufferedStreamService.BufferedWrappedMessageWithMemoryStream(GeneratedContracts.BufferedWrappedMessageWithMemoryStream request)
        {
            return base.Channel.BufferedWrappedMessageWithMemoryStream(request);
        }
        
        public void BufferedWrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body4)
        {
            GeneratedContracts.BufferedWrappedMessageWithMemoryStream inValue = new GeneratedContracts.BufferedWrappedMessageWithMemoryStream();
            inValue.Header = Header;
            inValue.Body4 = Body4;
            GeneratedContracts.BufferedWrappedMessageWithMemoryStreamResponse retVal = ((GeneratedContracts.IBufferedStreamService)(this)).BufferedWrappedMessageWithMemoryStream(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.IStreamedStreamService")]
    public interface IStreamedStreamService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedStreamOperation", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedStreamOperationRes" +
            "ponse")]
        System.IO.Stream StreamedStreamOperation(System.IO.Stream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedMemoryStreamOperat" +
            "ion", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedMemoryStreamOperat" +
            "ionResponse")]
        System.IO.MemoryStream StreamedMemoryStreamOperation(System.IO.MemoryStream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedWithNonStreamParam" +
            "etersOperation", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedWithNonStreamParam" +
            "etersOperationResponse")]
        void StreamedWithNonStreamParametersOperation(string s, int i);
        
        // CODEGEN: Generating message contract since the operation StreamedUnwrappedMessageWithStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedUnwrappedMessageWi" +
            "thStream", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedUnwrappedMessageWi" +
            "thStreamResponse")]
        GeneratedContracts.StreamedUnwrappedMessageWithStreamResponse StreamedUnwrappedMessageWithStream(GeneratedContracts.StreamedUnwrappedMessageWithStream request);
        
        // CODEGEN: Generating message contract since the operation StreamedUnwrappedMessageWithMemoryStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedUnwrappedMessageWi" +
            "thMemoryStream", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedUnwrappedMessageWi" +
            "thMemoryStreamResponse")]
        GeneratedContracts.StreamedUnwrappedMessageWithMemoryStreamResponse StreamedUnwrappedMessageWithMemoryStream(GeneratedContracts.StreamedUnwrappedMessageWithMemoryStream request);
        
        // CODEGEN: Generating message contract since the operation StreamedWrappedMessageWithStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedWrappedMessageWith" +
            "Stream", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedWrappedMessageWith" +
            "StreamResponse")]
        GeneratedContracts.StreamedWrappedMessageWithStreamResponse StreamedWrappedMessageWithStream(GeneratedContracts.StreamedWrappedMessageWithStream request);
        
        // CODEGEN: Generating message contract since the operation StreamedWrappedMessageWithMemoryStream is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IStreamedStreamService/StreamedWrappedMessageWith" +
            "MemoryStream", ReplyAction="http://contoso.com/service/test/IStreamedStreamService/StreamedWrappedMessageWith" +
            "MemoryStreamResponse")]
        GeneratedContracts.StreamedWrappedMessageWithMemoryStreamResponse StreamedWrappedMessageWithMemoryStream(GeneratedContracts.StreamedWrappedMessageWithMemoryStream request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedUnwrappedMessageWithStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.Stream Body1;
        
        public StreamedUnwrappedMessageWithStream()
        {
        }
        
        public StreamedUnwrappedMessageWithStream(int Header, System.IO.Stream Body1)
        {
            this.Header = Header;
            this.Body1 = Body1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedUnwrappedMessageWithStreamResponse
    {
        
        public StreamedUnwrappedMessageWithStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedUnwrappedMessageWithMemoryStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.MemoryStream Body2;
        
        public StreamedUnwrappedMessageWithMemoryStream()
        {
        }
        
        public StreamedUnwrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body2)
        {
            this.Header = Header;
            this.Body2 = Body2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedUnwrappedMessageWithMemoryStreamResponse
    {
        
        public StreamedUnwrappedMessageWithMemoryStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://wrapper/StreamedWrappedMessageWithStream", IsWrapped=true)]
    public partial class StreamedWrappedMessageWithStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public byte[] Body3;
        
        public StreamedWrappedMessageWithStream()
        {
        }
        
        public StreamedWrappedMessageWithStream(int Header, byte[] Body3)
        {
            this.Header = Header;
            this.Body3 = Body3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedWrappedMessageWithStreamResponse
    {
        
        public StreamedWrappedMessageWithStreamResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyWrapper", WrapperNamespace="http://wrapper/StreamedWrappedMessageWithMemoryStream", IsWrapped=true)]
    public partial class StreamedWrappedMessageWithMemoryStream
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://contoso.com/service/test")]
        public int Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/service/test", Order=0)]
        public System.IO.MemoryStream Body4;
        
        public StreamedWrappedMessageWithMemoryStream()
        {
        }
        
        public StreamedWrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body4)
        {
            this.Header = Header;
            this.Body4 = Body4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamedWrappedMessageWithMemoryStreamResponse
    {
        
        public StreamedWrappedMessageWithMemoryStreamResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStreamedStreamServiceChannel : GeneratedContracts.IStreamedStreamService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StreamedStreamServiceClient : System.ServiceModel.ClientBase<GeneratedContracts.IStreamedStreamService>, GeneratedContracts.IStreamedStreamService
    {
        
        public StreamedStreamServiceClient()
        {
        }
        
        public StreamedStreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public StreamedStreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StreamedStreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StreamedStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.IO.Stream StreamedStreamOperation(System.IO.Stream input)
        {
            return base.Channel.StreamedStreamOperation(input);
        }
        
        public System.IO.MemoryStream StreamedMemoryStreamOperation(System.IO.MemoryStream input)
        {
            return base.Channel.StreamedMemoryStreamOperation(input);
        }
        
        public void StreamedWithNonStreamParametersOperation(string s, int i)
        {
            base.Channel.StreamedWithNonStreamParametersOperation(s, i);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.StreamedUnwrappedMessageWithStreamResponse GeneratedContracts.IStreamedStreamService.StreamedUnwrappedMessageWithStream(GeneratedContracts.StreamedUnwrappedMessageWithStream request)
        {
            return base.Channel.StreamedUnwrappedMessageWithStream(request);
        }
        
        public void StreamedUnwrappedMessageWithStream(int Header, System.IO.Stream Body1)
        {
            GeneratedContracts.StreamedUnwrappedMessageWithStream inValue = new GeneratedContracts.StreamedUnwrappedMessageWithStream();
            inValue.Header = Header;
            inValue.Body1 = Body1;
            GeneratedContracts.StreamedUnwrappedMessageWithStreamResponse retVal = ((GeneratedContracts.IStreamedStreamService)(this)).StreamedUnwrappedMessageWithStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.StreamedUnwrappedMessageWithMemoryStreamResponse GeneratedContracts.IStreamedStreamService.StreamedUnwrappedMessageWithMemoryStream(GeneratedContracts.StreamedUnwrappedMessageWithMemoryStream request)
        {
            return base.Channel.StreamedUnwrappedMessageWithMemoryStream(request);
        }
        
        public void StreamedUnwrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body2)
        {
            GeneratedContracts.StreamedUnwrappedMessageWithMemoryStream inValue = new GeneratedContracts.StreamedUnwrappedMessageWithMemoryStream();
            inValue.Header = Header;
            inValue.Body2 = Body2;
            GeneratedContracts.StreamedUnwrappedMessageWithMemoryStreamResponse retVal = ((GeneratedContracts.IStreamedStreamService)(this)).StreamedUnwrappedMessageWithMemoryStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.StreamedWrappedMessageWithStreamResponse GeneratedContracts.IStreamedStreamService.StreamedWrappedMessageWithStream(GeneratedContracts.StreamedWrappedMessageWithStream request)
        {
            return base.Channel.StreamedWrappedMessageWithStream(request);
        }
        
        public void StreamedWrappedMessageWithStream(int Header, byte[] Body3)
        {
            GeneratedContracts.StreamedWrappedMessageWithStream inValue = new GeneratedContracts.StreamedWrappedMessageWithStream();
            inValue.Header = Header;
            inValue.Body3 = Body3;
            GeneratedContracts.StreamedWrappedMessageWithStreamResponse retVal = ((GeneratedContracts.IStreamedStreamService)(this)).StreamedWrappedMessageWithStream(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratedContracts.StreamedWrappedMessageWithMemoryStreamResponse GeneratedContracts.IStreamedStreamService.StreamedWrappedMessageWithMemoryStream(GeneratedContracts.StreamedWrappedMessageWithMemoryStream request)
        {
            return base.Channel.StreamedWrappedMessageWithMemoryStream(request);
        }
        
        public void StreamedWrappedMessageWithMemoryStream(int Header, System.IO.MemoryStream Body4)
        {
            GeneratedContracts.StreamedWrappedMessageWithMemoryStream inValue = new GeneratedContracts.StreamedWrappedMessageWithMemoryStream();
            inValue.Header = Header;
            inValue.Body4 = Body4;
            GeneratedContracts.StreamedWrappedMessageWithMemoryStreamResponse retVal = ((GeneratedContracts.IStreamedStreamService)(this)).StreamedWrappedMessageWithMemoryStream(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.IShapeService")]
    public interface IShapeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/IShapeService/DoSomething", ReplyAction="http://contoso.com/service/test/IShapeService/DoSomethingResponse")]
        GeneratedContracts.Shape DoSomething(GeneratedContracts.Shape parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IShapeServiceChannel : GeneratedContracts.IShapeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ShapeServiceClient : System.ServiceModel.ClientBase<GeneratedContracts.IShapeService>, GeneratedContracts.IShapeService
    {
        
        public ShapeServiceClient()
        {
        }
        
        public ShapeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ShapeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShapeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShapeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public GeneratedContracts.Shape DoSomething(GeneratedContracts.Shape parameter)
        {
            return base.Channel.DoSomething(parameter);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/service/test", ConfigurationName="GeneratedContracts.ISharePrices", CallbackContract=typeof(GeneratedContracts.ISharePricesCallback))]
    public interface ISharePrices
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://contoso.com/service/test/ISharePrices/RegisterForNotificationOneWay")]
        void RegisterForNotificationOneWay(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/ISharePrices/RegisterForNotificationTwoWay", ReplyAction="http://contoso.com/service/test/ISharePrices/RegisterForNotificationTwoWayRespons" +
            "e")]
        void RegisterForNotificationTwoWay(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISharePricesCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://contoso.com/service/test/ISharePrices/PriceOneWay")]
        void PriceOneWay(string symbol, float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/service/test/ISharePrices/PriceTwoWay", ReplyAction="http://contoso.com/service/test/ISharePrices/PriceTwoWayResponse")]
        void PriceTwoWay(string symbol, float price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISharePricesChannel : GeneratedContracts.ISharePrices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SharePricesClient : System.ServiceModel.DuplexClientBase<GeneratedContracts.ISharePrices>, GeneratedContracts.ISharePrices
    {
        
        public SharePricesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public SharePricesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public SharePricesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public SharePricesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public SharePricesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public void RegisterForNotificationOneWay(string symbol)
        {
            base.Channel.RegisterForNotificationOneWay(symbol);
        }
        
        public void RegisterForNotificationTwoWay(string symbol)
        {
            base.Channel.RegisterForNotificationTwoWay(symbol);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneratedContracts.IServiceKnownType")]
    public interface IServiceKnownType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceKnownType/DoSomething", ReplyAction="http://tempuri.org/IServiceKnownType/DoSomethingResponse")]
        void DoSomething(GeneratedContracts.BaseServiceKnownType arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceKnownTypeChannel : GeneratedContracts.IServiceKnownType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceKnownTypeClient : System.ServiceModel.ClientBase<GeneratedContracts.IServiceKnownType>, GeneratedContracts.IServiceKnownType
    {
        
        public ServiceKnownTypeClient()
        {
        }
        
        public ServiceKnownTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ServiceKnownTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServiceKnownTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServiceKnownTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void DoSomething(GeneratedContracts.BaseServiceKnownType arg)
        {
            base.Channel.DoSomething(arg);
        }
    }
}
